name: Javascript Linter

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name : Install NodeJS
        uses: actions/setup-node@v6.1.0
        with:
          node-version: '18'

      - name: Checkout codebase
        uses: actions/checkout@v6

      - name: Install dependencies
        run: npm ci 
        
      - name : Eslint
        run: npm run lint

  deploy:
    runs-on: ubuntu-latest
    
    needs: [lint]

    if: github.ref == 'refs/heads/master'

    steps:
      - name: Checkout codebase
        uses: actions/checkout@v6

      - name: Copy SSH keys
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" >> ~/.ssh/id_ed25519
          echo "${{ secrets.SSH_PUBLIC_KEY }}" >> ~/.ssh/id_ed25519.pub
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy on SSH
        run: |
          ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "mkdir salut"
