name: Javascript Linter

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name : Install NodeJS
        uses: actions/setup-node@v6.1.0
        with:
          node-version: '18'

      - name: Checkout codebase
        uses: actions/checkout@v6

      - name: Install dependencies
        run: npm ci 
        
      - name : Eslint
        run: npm run lint
